services:
  - type: web
    name: finterminal
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: KOTAK_CONSUMER_KEY
        sync: false
      - key: KOTAK_CONSUMER_SECRET
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
